name: Test

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install valgrind
      - name: Build compiler and interpreter
        run: make
      - name: Check for memory leaks in compiler
        run: |
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./compiler.o examples/test.foo
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./compiler.o examples/test_if_2.foo
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./compiler.o examples/test_pointers_2.foo
      - name: Check for memory leaks in interpreter
        run: |
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./interpreter.o examples/test.foo.bytecode
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./interpreter.o examples/test_if_2.foo.bytecode
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./interpreter.o examples/test_pointers_2.foo.bytecode
      - name: Check for memory leaks in cross-assembler
        run: |
          ./compiler.o examples/test_cross.foo
          valgrind --leak-check=full --errors-for-leak-kinds=all --error-exitcode=1 ./cross_assembler.o examples/test_cross.foo.bytecode
